import { MessageType } from "./types/ChatWindow/types";

export const dummyMessages: MessageType[] = [
  {
    messageId: "1",
    messageBody: "Example message",
    senderId: "2",
    senderImageUrl: "/general/nikita-kek.jpg",
    senderName: "Nikita Syrotenko",
    sentTime: 1704693861,
    viewed: false,
  },
  {
    messageId: "2",
    messageBody: "Example message",
    senderId: "2",
    senderImageUrl: "/general/nikita-kek.jpg",
    senderName: "Nikita Syrotenko",
    sentTime: 1704693861,
    viewed: true,
  },
  {
    messageId: "3",
    messageBody: "Example message",
    senderId: "1",
    senderImageUrl: "/general/main.HEIC",
    senderName: "Omar Hamid",
    sentTime: 1704693861,
    viewed: false,
  },
  {
    messageId: "4",
    messageBody: "Example message",
    senderId: "1",
    senderImageUrl: "/general/main.HEIC",
    senderName: "Omar Hamid",
    sentTime: 1704693861,
    viewed: true,
  },
  {
    messageId: "5",
    messageBody: "Example message",
    senderId: "2",
    senderImageUrl: "/general/nikita-kek.jpg",
    senderName: "Nikita Syrotenko",
    sentTime: 1704693861,
    viewed: false,
  },
  {
    messageId: "6",
    messageBody: "Example message",
    senderId: "1",
    senderImageUrl: "/general/main.HEIC",
    senderName: "Omar Hamid",
    sentTime: 1704693861,
    viewed: true,
  },
  {
    messageId: "7",
    messageBody: "Example message",
    senderId: "2",
    senderImageUrl: "/general/nikita-kek.jpg",
    senderName: "Nikita Syrotenko",
    sentTime: 1704693861,
    viewed: false,
  },
  {
    messageId: "8",
    messageBody: "Example message",
    senderId: "1",
    senderImageUrl: "/general/main.HEIC",
    senderName: "Omar Hamid",
    sentTime: 1704693861,
    viewed: true,
  },
  {
    messageId: "9",
    messageBody: "Example message",
    senderId: "2",
    senderImageUrl: "/general/nikita-kek.jpg",
    senderName: "Nikita Syrotenko",
    sentTime: 1704693861,
    viewed: false,
  },
  {
    messageId: "110",
    messageBody: "Example message",
    senderId: "1",
    senderImageUrl: "/general/main.HEIC",
    senderName: "Omar Hamid",
    sentTime: 1704693861,
    viewed: false,
  },
];
