import { User } from "./types/User";

export const dummyAllUsers: User[] = [
  {
    id: "65bffe74854dc4cfb58c5250",
    name: "Omar Hamid",
    residency: "Calgary, AB",
    email: "omarhamid@example.com",
    imageSrc: "/general/main.HEIC",
    isOnline: true,
    lastSeenPermission: true,
    lastSeenTime: new Date().getTime(),
  },
  {
    imageSrc: "/general/maksim-kek.jpg",
    name: "Maksim Sapun",
    id: "65c1c34a64a8464ceeee1af2",
    email: "maksimsapun@example.com",
    residency: "Calgary, AB",
    isOnline: false,
    lastSeenPermission: false,
    lastSeenTime: new Date("2024-01-04T15:30:45Z").getTime(),
  },
  {
    imageSrc: "/general/nikita-kek.jpg",
    name: "Nikita Syrotenko",
    id: "65c1c42164a8464ceeee1af3",
    email: "nikitasirotenko@example.com",
    residency: "Calgary, AB",
    isOnline: false,
    lastSeenPermission: true,
    lastSeenTime: new Date().getTime() - 1000,
  },
  {
    imageSrc: "/general/ihor-kek.jpg",
    name: "Ihor Chupaha",
    id: "65c1c4bc64a8464ceeee1af4",
    email: "ihorchupaha@example.com",
    residency: "Calgary, AB",
    isOnline: true,
    lastSeenPermission: true,
    lastSeenTime: new Date("2024-01-04T15:30:45Z").getTime(),
  },
  // {
  //   imageSrc: "/general/omar-kek.JPG",
  //   name: "Omar Hamid",
  //   id: "5",
  //   email: "omarhamid@example.com",
  //   residency: "Calgary, AB",
  //   isOnline: false,
  //   lastSeenPermission: true,
  //   lastSeenTime: new Date().getTime() - 10000000,
  // },
];
